### ISSUE TITLE
Error on slide 11, lecture presentation 3 (Raspberry Pi)

### ISSUE THREAD

**Issue by lestheprof** [arm-university/Embedded-Linux-Education-Kit#1]
Slide states:

Interrupt type:
Slow: traditional interrupt (e.g. coming from a disk driver)
Fast: interrupt corresponding to very fast operations (e.g. processing a keyboard input)

The examples are the wrong way round.

**Comment by MarkA21** [comment]
Hey - thanks for raising this point. I will take a look at it and amend if appropriate!

**Comment by MarkA21** [comment]
I have reviewed the slide and believe the material is quite vague/arbitrary. I have modified the slide to refer to fast interrupt requests (FIQ) and standard interrupt requests (IRQ). The example of the keyboard still relates to the FIQ but instead of being about the duration of the act, it is more to do with the need to respond to it as it occurs.

I have attached the updated powerpoint here:
[Lecture Presentation_03.pptx](https://github.com/arm-university/Embedded-Linux-Education-Kit/files/8042792/Lecture.Presentation_03.pptx)

If you have different thoughts/opinions about this let me know.

If not - I will push the change to the repo.

Thanks,
Mark

**Comment by lestheprof** [comment]
OK:

It's probably worth noting that FIQ has higher priority - that is, a fast
interrupt can interrupt the code servicing an IRQ , but not vice versa.

--Leslie Smith


Mark wrote:
> I have reviewed the slide and believe the material is quite
> vague/arbitrary. I have modified the slide to refer to fast interrupt
> requests (FIQ) and standard interrupt requests (IRQ). The example of the
> keyboard still relates to the FIQ but instead of being about the duration
> of the act, it is more to do with the need to respond to it as it occurs.
>
> I have attached the updated powerpoint here:
> [Lecture
> Presentation_03.pptx](https://github.com/arm-university/Embedded-Linux-Education-Kit/files/8042792/Lecture.Presentation_03.pptx)
>
> If you have different thoughts/opinions about this let me know.
>
> If not - I will push the change to the repo.
>
> Thanks,
> Mark
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/arm-university/Embedded-Linux-Education-Kit/issues/1#issuecomment-1035164579
> You are receiving this because you authored the thread.
>
> Message ID:
> ***@***.***>


-- 
Prof Leslie Smith (Emeritus)
Computing Science & Mathematics,
University of Stirling, Stirling FK9 4LA
Scotland, UK
Tel +44 1786 467435
Web: http://www.cs.stir.ac.uk/~lss
Blog: http://lestheprof.com

**Comment by MarkA21** [comment]
That's a good point. Amended slide to include FIQ priority over IRQ. Will push changes to repo.

[Lecture.Presentation_03.pptx](https://github.com/arm-university/Embedded-Linux-Education-Kit/files/8048102/Lecture.Presentation_03.pptx)

Thanks for the input. Will close issue but feel free to reach out again.
